language: php

php:
  - 7.3

install:
  - composer install

script:
  - find src/ -name "*.php" | while read line; do php -l $line; done;
  - phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
